name: ci
on:  # Triggers on PRs.
  - pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: always

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
